### ISSUE TITLE
Issues about the :SubstituteChoices command

### ISSUE THREAD

**Issue by roccomao** [inkarkat/vim-PatternsOnText#1]
First of all, thank you for your many vim plugins, very useful. See you updated the `:SubstituteChoices` command, and there are some other requests or bugs:

1. Although I see `Relying on 'cursorline' / 'cursorcolumn' has been a poor kludge` in your commit message, but this will be clearer probably. Therefore, if the `:SubstituteChoices` command has `:s_g` flag, can matches be replaced in place, instead of displaying result after all matches of the line are replaced completely? Just like the built-in `:substitute` command.
2. When using your current implementation, matches at the beginning of a line are not highlighted correctly, as follows:
![highlight](https://user-images.githubusercontent.com/30104601/173399961-ef650edb-aafa-4ff9-95b4-7aa9de7d9559.png)
![reproduce](https://user-images.githubusercontent.com/30104601/173400035-5eedfb18-25c4-4726-a90b-78bae99c7a3d.gif)
4. When the `:SubstituteChoices` command has `:s_c` flag, the command line will prompt for more information, but always need to refresh the prompt information at some point. After testing, I always need to turn pages at the sixth and tenth positions of all matches, as follows:
![more](https://user-images.githubusercontent.com/30104601/173406544-3a5a1de5-7cc6-4702-b1dd-5441119f0d73.png)
![more_page](https://user-images.githubusercontent.com/30104601/173407831-a1c58879-dec6-4415-b9cf-3eb14b070135.gif)
It might be related to the screen size. The above test is tested when `:s_c` flag is included in full screen, the same, if `:s_c` flag is not included, everything is normal. But when the screen size becomes smaller, even if `:s_c` flag is not included, a similar situation occurs and the location is not certain at this time, as follow:
![small](https://user-images.githubusercontent.com/30104601/173410355-3224ac1b-3d6b-4165-8252-a025a0487360.gif)

-----------------------------------------

**My Environment**
 - `vim-PatternsOnText` current latest version ( 09bcf7c )
 - latest dependency: ingo-library.vim plugin ( version 1.045, [35ecb64](https://github.com/inkarkat/vim-ingo-library/commit/35ecb646d478ccd925accd895b46cb523853b3a3) )
 - OS: Windows 10 21H2 ( 19044.1741 )
 - Vim version: 8.2.2825
![version](https://user-images.githubusercontent.com/30104601/173414369-ca17f587-8aaf-4860-bfc3-2e574c22a3ec.png)

**Comment by inkarkat** [comment]
Thank you for your very precise and detailed feedback; it's been a pleasure to read!

---

> can matches be replaced in place, instead of displaying result after all matches of the line are replaced completely? Just like the built-in `:substitute` command.

The built-in `:substitute/.../.../gc` command indeed highlights the current match in the buffer, that would be ideal for `:SubstituteChoices`, too. Unfortunately, the `:s_c` confirm cannot be modified / hooked into, and that special highlighting only happens when the flag is given. So the only way for the plugin to use that would be to have two queries, first for the built-in `:s_c` flag (doing the highlighting) and then for the plugin's own query. Not good.

Therefore, the plugin has to emulate the highlighting elsewhere. Vim could be extended (with a new flag) that would still trigger the highlighting update, but not the confirmation query; the plugin could then pass that new flag.

---

> When using your current implementation, matches at the beginning of a line are not highlighted correctly

Oh dang, that was an off-by-one error in my implementation. It's been [fixed](https://github.com/inkarkat/vim-ingo-library/commit/9346d590138f7d805fdfad346c4808688a8592ac).

---

> always need to refresh the prompt information at some point

I can reproduce that, too. The query output is done on each match of the `:substitute` iteration, after a `:redraw`. I guess Vim doesn't do proper accounting of printed lines during that iteration, only after the `:substitute` is done, and that's why the _hit-enter_ prompt occurs erratically. This would have to be fixed in Vim, too.

---

During testing, I've found some additional minor issues; https://github.com/inkarkat/vim-ingo-library/commit/439c576a229769615fa1060cb8d14686c54a22c1 and https://github.com/inkarkat/vim-PatternsOnText/commit/921f56b36fd548b1142f31ffca45da189b6ab81e contain the fixes.
